export enum Services {
  AUTH = 'AUTH_SERVICE',
  USER = 'USER_SERVICE',
  CUSTOM_JWT = 'CUSTOM_JWT_SERVICE',

  GROUP = 'GROUP_SERVICE',
  GROUP_MESSAGE = 'GROUP_MESSAGE_SERVICE',
  GROUPS_RECIPIENTS = 'GROUPS_RECIPIENTS_SERVICE',

  REDIS_CLIENT = 'REDIS_CLIENT_SERVICE',
  REDIS_SOCKET = 'REDIS_SOCKET_SERVICE',
}
