export enum Services {
  AUTH = 'AUTH_SERVICE',
  USER = 'USER_SERVICE',
  CUSTOM_JWT = 'CUSTOM_JWT_SERVICE',

  GROUP = 'GROUP_SERVICE',
  GROUP_MESSAGE = 'GROUP_MESSAGE_SERVICE',
  GROUPS_RECIPIENTS = 'GROUPS_RECIPIENTS_SERVICE',

  GATEWAY_SESSION_MANAGER = 'GATEWAY_SESSION_MANAGER',

  CONVERSATION = 'CONVERSATION_SERVICE',
  CONVERSATION_MESSAGE = 'CONVERSATION_MESSAGE_SERVICE',

  FRIEND = 'FRIEND_SERVICE',
  FRIEND_REQUEST = 'FRIEND_REQUEST_SERVICE',
}
